### ISSUE TITLE
Save file is broken in new commit

### ISSUE THREAD

**Issue by tigrazone** [AdamYuan/SparseVoxelOctree#20]
Previously I use commit [Avoid using samplers per texture](https://github.com/AdamYuan/SparseVoxelOctree/commit/459e4c21058e425790e17c8c97b18b55bcf69869) and save to hdr is worked ok. 
In new commit save to hdr is broken and program abnormally exit.

**Comment by AdamYuan** [comment]
Fixed already (https://github.com/AdamYuan/SparseVoxelOctree/commit/3b175fc872552a859adba675620149c7a2020849), thanks for the report

**Comment by tigrazone** [comment]
In 3 exr saving functions last lines was
	staging_buffer->Unmap();

	return pixels;
	
but on new commits is
	return pixels;
	
Is absense of  staging_buffer->Unmap();  dont create memory leak?

**Comment by AdamYuan** [comment]
Buffer created with VMA_ALLOCATION_CREATE_MAPPED_BIT flag is mapped by default, so there's no need to unmap it

**Comment by tigrazone** [comment]
thank you for explanation
