### ISSUE TITLE
I want to add tonemapper to code. Where to add?

### ISSUE THREAD

**Issue by tigrazone** [AdamYuan/SparseVoxelOctree#21]
Where is in code now convert of hdr accumulated image to show to screen - is it right it is path_tracer_viewer_main.frag?
I want to add tone mapper and save to ldr - to png, jpg. In which source code I must add my code?
[dep/MyVK/src/imgui/ImGuiRenderer.cpp](https://github.com/AdamYuan/SparseVoxelOctree/commit/6fd35471f5ca5bf8d0ac16c8221ac0218ee2eb50#diff-a45f569fd57d0a7d8c7769997179a3653c2bd41a8b0f98f55b63c1c9a815b131) have encoded code. 
Can you show source of this encoded code?

**Comment by AdamYuan** [comment]
It's in path_tracer_viewer_gen.frag i think:
```glsl
// ...
	if (uViewType == 0) {
		vec4 color = imageLoad(uColor, ivec2(gl_FragCoord.xy));
		oColor = vec4(pow(color.xyz, vec3(1.0 / 2.2)), 1.0);
	} else if (uViewType == 1) {
// ...
```
