### ISSUE TITLE
How to save ldr - to png or jpg?

### ISSUE THREAD

**Issue by tigrazone** [AdamYuan/SparseVoxelOctree#22]
I need to save tonemapped png or jpg, not hdr image.
How to do it? 
Or maybe implement it in code, please

**Comment by AdamYuan** [comment]
you can use online tools such as https://viewer.openhdr.org/

**Comment by tigrazone** [comment]
Maybe you dont understand me.
I want to save output from window in png or jpg format.
I dont need outside tool for convert hdr to ldr or so.

**Comment by AdamYuan** [comment]
Sorry, but I don't think it's appropriate to export as png or jpg in a path tracer since the resulting image is an HDR image by default.
You can press 'X' to hide the UI and take a window screenshot to get a png image

**Comment by tigrazone** [comment]
ok. thank you
