### ISSUE TITLE
Bounce vs real frame number

### ISSUE THREAD

**Issue by tigrazone** [AdamYuan/SparseVoxelOctree#24]
Hello.
Why you use m_bounce to calculate spp for divide accumulated but not use real frame number?

https://github.com/AdamYuan/SparseVoxelOctree/blob/3b175fc872552a859adba675620149c7a2020849/shader/path_tracer.comp#L123

**Comment by AdamYuan** [comment]
I store 'samples per pixel' with the last array entry of uSobol array, and its index is (uBounce + 1) * 2

**Comment by tigrazone** [comment]
Little bit strange ;-)
I find it in code
https://github.com/AdamYuan/SparseVoxelOctree/blob/3b175fc872552a859adba675620149c7a2020849/src/PathTracer.cpp#L184

Why you do it this way?

**Comment by tigrazone** [comment]
uBounce/m_bounce is not an frame number. 
uBounce/m_bounce is max depth of tracing of ray

**Comment by AdamYuan** [comment]
and uDimension is (m_bounce + 1) * 2

**Comment by AdamYuan** [comment]
only for spp

**Comment by tigrazone** [comment]
thank you for answers
