### ISSUE TITLE
Any benchmarks?

### ISSUE THREAD

**Issue by warvstar** [AdamYuan/SparseVoxelOctree#3]
Hey just wondering if you can tell me how fast the can build an svo on a couple datasets. Thanks

**Comment by AdamYuan** [comment]
I use Dell Precision 5520 with NVIDIA Quadro M1200/PCIe/SSE2 (linux + bumblebee), which is not a typical graphics card. And there seems to be a huge performance gap between my GPU and some modern GPUs such as GTX 1060 and RTX cards. Many GPU programs' speed on my laptop is far slower than their benchmark result on modern GPUs (for example, a cuda BVH traversal demo said it can reach 900Mray/s on a GTX 1080 but I only got 100Mray/s on my laptop). So for now I don't have the condition to do a meaningful benchmark.

**Comment by AdamYuan** [comment]
see https://github.com/AdamYuan/SparseVoxelOctree#improvements
