### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Qix-** [AdamYuan/SparseVoxelOctree#8]
Hi there, what's the license for this code?

If you don't care about its usage and are unsure, might I suggest the MIT license?

**Comment by AdamYuan** [comment]
Probably.
The reason I haven't set a license is that my octree traversal code is "translated" from the CUDA code in https://code.google.com/archive/p/efficient-sparse-voxel-octrees/.
I'm not sure how to deal with it. Do I just need to copy its license text on the top of the code?

**Comment by Qix-** [comment]
Define 'translated' here? Did you copy/paste and then spruce up? Or did you write new code based on the process/concepts/ideas/algorithm?

If the former, then _at least_ the parts that were copied must be individually licensed and copyrighted under the original license (BSD 3 clause is usually OK too, fwiw). The rest of the code you wrote originally can be licensed however you'd like.

In the latter case it's a bit more grey-area but you can probably license it however you'd like.

Given that the original is pretty liberally licensed, it might be best/safest to just license under BSD 3 clause with an attribution to the original author(s) in e.g. header comments or a README mention or something, where applicable :)

Also thanks for the response! 🙂

**Comment by AdamYuan** [comment]
The license is finally added. Thanks for your help!

**Comment by Qix-** [comment]
No problem :) Thanks for adding it!
